// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package roo.ph.repository;

import org.springframework.transaction.annotation.Transactional;
import roo.ph.repository.OrderBookRepository;

privileged aspect OrderBookRepository_Roo_Jpa_Repository {
    
    declare @type: OrderBookRepository: @Transactional(readOnly = true);
    
}
